CUSTOM_IMAGE_MOUNT_POINT := oem
CUSTOM_IMAGE_PARTITION_SIZE := 31457280
CUSTOM_IMAGE_FILE_SYSTEM_TYPE := ext4
CUSTOM_IMAGE_DICT_FILE := device/khadas/s4vim/oem/oem_dict.txt
CUSTOM_IMAGE_SELINUX := true
CUSTOM_IMAGE_COPY_FILES := device/khadas/s4vim/oem/oem.prop:oem.prop